name: BuildDeploy
on: push
jobs:
  
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3 
  
  installDependencies:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: npm ci
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: npm run build
  
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: tests
        run: npm test    
  
     
  deploy:
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "desplegando" 