name: BuildDeploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: run test
        run: npm test  
  deploy:
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "desplegando" 