name: BuildDeploy
on: push

jobs:
  
  installDependencies:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3      
      - name: install
        run: npm ci
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: npm run build
  
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3    
      - name: tests
        run: npm test    
  
     
  deploy:
    needs: tests 
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "desplegando" 